project_id = "xngukxdccwsgsovzmdzj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[functions.create-payment-order]
verify_jwt = true

[functions.create-custom-contest-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.verify-custom-contest-payment]
verify_jwt = false

[functions.debug-cashfree]
verify_jwt = false