// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xngukxdccwsgsovzmdzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZ3VreGRjY3dzZ3NvdnptZHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDc4NzAsImV4cCI6MjA2ODE4Mzg3MH0.FrSSgaFbovqucSkjdfHqVoi-oxpg4cTCa_kXihgtCW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: false,
    autoRefreshToken: false,
  }
});